name: destroy-dynamo

on:
  workflow_call:
    inputs:
      aws-assume-role-arn:
        required: true
        type: string

      aws-region:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Destroy table
        run: |

          chmod +x infra/scripts/*.sh

          ./infra/scripts/destroy-table.sh
